[package]
name = "bevy_ui_inspector"
version = "0.3.0"
edition = "2021"
description = "A tool for inspecting bevy ui"
license = "MIT OR Apache-2.0"
repository = "https://github.com/mahulst/bevy_ui_inspector"
readme = "README.md"

[dependencies]
bevy = "0.15"
bevy_egui = "0.32.0"
